### PR TITLE
Swich to rpm to check if updates are still valid

### PR DESCRIPTION
**Pull request by reaperzn**
This fixes issue #66 and also #98

### CODE REVIEW

**Review by popindavibe — APPROVED** [review]
Change tested & approved.

**Comment by reaperzn** [comment]
Please confirm this was tested against RHEL/CentOS 6, RHEL/CentOS 7, Fedora 26, Fedora 27

**Comment by popindavibe** [comment]
Tested OK on Fedora 26, Fedora 27, CentOS 6, CentOS 7

**note:** version of auter used as part of this PR contains error fixed by merged #100

**Comment by Pingue** [comment]
Merging on behalf of @popindavibe :)

**Pull request merged**
