### PR TITLE
Preparing for 0.11 release. Currently there is only automatic testing…

### PR DESCRIPTION
**Pull request by reaperzn**
… for spellcheck and shellcheck

### CODE REVIEW

**Comment by reaperzn** [comment]
Full testing still required. Please Add comments to this PR as testing is completed. 
Testing required:
RHEL/CentOS 6
RHEL/CentOS 7
Fedora 26
Fedora 27
Ubuntu 16.04

**Comment by rhodesn** [comment]
# CentOS6, CentOS7, Fedora26, Fedora27
## Docker CI

Docker builds all complete successfully. Docker-CE is not available for CentOS6
so is untested.

## auter status
- [ pass ] auter --status
  - /var/lib/auter/enabled exists

- [ pass ] auter --disable
  - /var/lib/auter/enabled does not exist

- [ pass ] auter --enable
  - /var/lib/auter/enabled exists

- [ pass ] auter --help
  - same output when running 'auter' without arguments

## update manually
- [ pass ] auter --prep
  - updates downloaded to /var/cache/auter/default
  - pre/post prep scripts ran successfully, messages logged to syslog

- [ pass ]auter --apply
  - no upates available after running
  - pre/post apply scripts ran successfully, messages logged to syslog

- [ pass ] auter --reboot working
  - machine rebooted
  - pre/post reboot scripts ran successfully, messages logged to syslog

## update via cron
- [ pass ] auter --prep --stdout
  - updates downloaded to /var/cache/auter/default
  - pre/post prep scripts ran successfully, messages logged to syslog
  - output from auter also mailed to root user on CentOS boxes, output logged to
    syslog on Fedora systems

- [ pass ] auter --apply --stdout
  - no updates available after running
  - pre/post scripts ran successfully, messages logged to syslog
  - output from auter also mailed to root user on CentOS boxes, output logged to
    syslog on Fedora systems

- [ pass ] auter --reboot --stdout
  - server rebooted after 2 minutes
  - pre/post scripts ran successfully 
  - output from auter also mailed to the root user on CentOS, output logged to
    syslog on Fedora

## functionality testing
- [ pass ] rotate_files function is correctly rotating files prep and apply last
  run logs.

- [ pass ] rpms generated via the rpmbuild script successfully installed on all
  distributions.

**Comment by rhodesn** [comment]
During testing we noticed that the check_package_manager_lock function was preventing auter --apply even though no updates were available. Caused by:

```
[[ "${APPLY}" ]] && check_package_manager_lock && apply_updates
```

That function call should be moved to within the IF statement for the yum update:

Line: 121
```
 if [[ "${RC}" -eq 100 ]]; then
```

**Comment by rhodesn** [comment]
Further tests for check_package_manager_lock:

**/var/run/yum.pid exists**
- auter --prep waited for lock to release and continued successfully when the lock was released
- auter --prep waited for lock to release and successfully exited  after 5 retry attempts
- auter --apply waited for lock to release and continued successfully when the lock was released
- auter --apply with updates pending waited for the lock, and successfully exited after 5 retry attempts
- auter --apply with no updates pending also waited for the lock - this is mentioned in the previous comment

**Comment by rhodesn** [comment]
Further tests for **PREPOUTPUT**:
The log files last-prep-output-default are being populated with the prep output correctly.

There is one caveat that the last-prep-output-default file is not created when there are no updates to apply, however the rotate_file function still gets called which causes the following:

```
root@centos7:/var/lib/auter > ll
total 40
-rw-r--r--. 1 root root  119 Mar 15 14:45 enabled
-rw-r--r--. 1 root root 2456 Mar 15 14:26 last-apply-output-default
-rw-r--r--. 1 root root 2456 Mar 15 12:56 last-apply-output-default.1
-rw-r--r--. 1 root root 2456 Mar 15 12:55 last-apply-output-default.2
-rw-r--r--. 1 root root 2456 Mar 15 12:55 last-apply-output-default.3
-rw-r--r--. 1 root root 2456 Mar 15 12:55 last-apply-output-default.4
-rw-r--r--. 1 root root 1472 Mar 15 14:20 last-prep-output-default.1
-rw-r--r--. 1 root root 1472 Mar 15 12:56 last-prep-output-default.2
-rw-r--r--. 1 root root 1472 Mar 15 12:55 last-prep-output-default.3
-rw-r--r--. 1 root root 1472 Mar 15 12:55 last-prep-output-default.4
```

**Comment by rhodesn** [comment]
Further test for **AUTOREBOOT**:
- When no updates to install, auter correctly skipped the reboot process.
- Afterinstalling updates, auter correctly rebooted the server as per the usual process.

**Review by Pingue — APPROVED** [review]
Code all looks good

**Pull request merged**
