### PR TITLE
Schedule the reboot and update PATH for lsof

### PR DESCRIPTION
**Pull request by rhodesn**
**Reboot timing etc open to debate**

Schedule the auter --reboot to take place one auter has finished
updating and update PATH to include /usr/sbin and /usr/local/sbin for
lsof run by crontab.

Resolves rackerlabs/auter/issues/157.

### CODE REVIEW

**Comment by rhodesn** [comment]
We could also do something along the lines of.
```sh
(while test -f $PIDFILE ; do sleep 1; done; auter --reboot)&
```

**Comment by rippiedoos** [comment]
The diff I came up with:
```
--- conditional-reboot.sh-orig	2018-05-31 13:14:28.877790528 +0200
+++ conditional-reboot.sh	2018-05-31 13:15:36.895790946 +0200
@@ -51,7 +51,7 @@
 fi
 
 # Identify if there are any libraries that are running but deleted
-LIBCHECK=$(lsof | grep lib | grep DEL)
+LIBCHECK=$(PATH=/usr/sbin:${PATH} lsof | grep lib | grep DEL)
 [[ -n "${LIBCHECK}" ]] && REBOOTREQURIRED+=("detected deleted libraries")
 
 # This is primarily for Debian and Ubuntu
@@ -78,7 +78,7 @@
     logit "Rebooting because ${REBOOTMATCH}"
   done
   logit "Rebooting server"
-  auter --reboot
+  (while test -f ${PIDFILE} ; do sleep 1; done; auter --reboot) &
 else
   logit "Reboot not required"
 fi
```

This works like a charm on Oracle Linux!

**Comment by rhodesn** [comment]
Thank you for testing this @rippiedoos! I've updated the PR to use the while check, but have left the longer PATH in as I can't see any drawbacks to it.

**Comment by rippiedoos** [comment]
I think the logit-line above the reboot command isn't accurate in the PR. It doesn't take 4 minutes anymore but less (maybe). Maybe 'Scheduling reboot of the server' would be more accurate?

**Comment by rhodesn** [comment]
Nice spot, updated.

**Comment by reaperzn** [comment]
@nrhodes91 Please rename this file to 99-conditionalReboot.sh

Assuming the numbering convention is followed, this does resolve the issue that was raised. We can leave the issue #157 open to have the documentation updated as a separate PR as I would like to implement a core change to the auter file which would do that script name validation.

**Comment by rhodesn** [comment]
@reaperzn filename updated. I'll look into the contrib docs update as well.

**Review by reaperzn — APPROVED** [review]
All looks good

**Pull request merged**
